//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ESTIMATEModel", "FK_ItemInfo_CatagoryInfo", "CatagoryInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BuySallsProject.CatagoryInfo), "ItemInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuySallsProject.ItemInfo), true)]
[assembly: EdmRelationshipAttribute("ESTIMATEModel", "FK_SaleInfo_CatagoryInfo", "CatagoryInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BuySallsProject.CatagoryInfo), "SaleInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuySallsProject.SaleInfo), true)]
[assembly: EdmRelationshipAttribute("ESTIMATEModel", "FK_OrderInfo_CustomarInfo", "CustomarInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BuySallsProject.CustomarInfo), "OrderInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuySallsProject.OrderInfo), true)]
[assembly: EdmRelationshipAttribute("ESTIMATEModel", "FK_SaleInfo_CustomarInfo", "CustomarInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BuySallsProject.CustomarInfo), "SaleInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuySallsProject.SaleInfo), true)]
[assembly: EdmRelationshipAttribute("ESTIMATEModel", "FK_EmpolyInfo_EmpolyDipartment", "EmpolyDipartment", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BuySallsProject.EmpolyDipartment), "EmpolyInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuySallsProject.EmpolyInfo), true)]
[assembly: EdmRelationshipAttribute("ESTIMATEModel", "FK_SelayInformation_EmpolyInfo", "EmpolyInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BuySallsProject.EmpolyInfo), "SelayInformation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuySallsProject.SelayInformation), true)]
[assembly: EdmRelationshipAttribute("ESTIMATEModel", "FK_OrderInfo_ItemInfo", "ItemInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BuySallsProject.ItemInfo), "OrderInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuySallsProject.OrderInfo), true)]

#endregion

namespace BuySallsProject
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ESTIMATEEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ESTIMATEEntities object using the connection string found in the 'ESTIMATEEntities' section of the application configuration file.
        /// </summary>
        public ESTIMATEEntities() : base("name=ESTIMATEEntities", "ESTIMATEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ESTIMATEEntities object.
        /// </summary>
        public ESTIMATEEntities(string connectionString) : base(connectionString, "ESTIMATEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ESTIMATEEntities object.
        /// </summary>
        public ESTIMATEEntities(EntityConnection connection) : base(connection, "ESTIMATEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CatagoryInfo> CatagoryInfoes
        {
            get
            {
                if ((_CatagoryInfoes == null))
                {
                    _CatagoryInfoes = base.CreateObjectSet<CatagoryInfo>("CatagoryInfoes");
                }
                return _CatagoryInfoes;
            }
        }
        private ObjectSet<CatagoryInfo> _CatagoryInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomarInfo> CustomarInfoes
        {
            get
            {
                if ((_CustomarInfoes == null))
                {
                    _CustomarInfoes = base.CreateObjectSet<CustomarInfo>("CustomarInfoes");
                }
                return _CustomarInfoes;
            }
        }
        private ObjectSet<CustomarInfo> _CustomarInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EmpolyDipartment> EmpolyDipartments
        {
            get
            {
                if ((_EmpolyDipartments == null))
                {
                    _EmpolyDipartments = base.CreateObjectSet<EmpolyDipartment>("EmpolyDipartments");
                }
                return _EmpolyDipartments;
            }
        }
        private ObjectSet<EmpolyDipartment> _EmpolyDipartments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EmpolyInfo> EmpolyInfoes
        {
            get
            {
                if ((_EmpolyInfoes == null))
                {
                    _EmpolyInfoes = base.CreateObjectSet<EmpolyInfo>("EmpolyInfoes");
                }
                return _EmpolyInfoes;
            }
        }
        private ObjectSet<EmpolyInfo> _EmpolyInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemInfo> ItemInfoes
        {
            get
            {
                if ((_ItemInfoes == null))
                {
                    _ItemInfoes = base.CreateObjectSet<ItemInfo>("ItemInfoes");
                }
                return _ItemInfoes;
            }
        }
        private ObjectSet<ItemInfo> _ItemInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<number> numbers
        {
            get
            {
                if ((_numbers == null))
                {
                    _numbers = base.CreateObjectSet<number>("numbers");
                }
                return _numbers;
            }
        }
        private ObjectSet<number> _numbers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderInfo> OrderInfoes
        {
            get
            {
                if ((_OrderInfoes == null))
                {
                    _OrderInfoes = base.CreateObjectSet<OrderInfo>("OrderInfoes");
                }
                return _OrderInfoes;
            }
        }
        private ObjectSet<OrderInfo> _OrderInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SaleInfo> SaleInfoes
        {
            get
            {
                if ((_SaleInfoes == null))
                {
                    _SaleInfoes = base.CreateObjectSet<SaleInfo>("SaleInfoes");
                }
                return _SaleInfoes;
            }
        }
        private ObjectSet<SaleInfo> _SaleInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SelayInformation> SelayInformations
        {
            get
            {
                if ((_SelayInformations == null))
                {
                    _SelayInformations = base.CreateObjectSet<SelayInformation>("SelayInformations");
                }
                return _SelayInformations;
            }
        }
        private ObjectSet<SelayInformation> _SelayInformations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CatagoryInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCatagoryInfoes(CatagoryInfo catagoryInfo)
        {
            base.AddObject("CatagoryInfoes", catagoryInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomarInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomarInfoes(CustomarInfo customarInfo)
        {
            base.AddObject("CustomarInfoes", customarInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmpolyDipartments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmpolyDipartments(EmpolyDipartment empolyDipartment)
        {
            base.AddObject("EmpolyDipartments", empolyDipartment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmpolyInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmpolyInfoes(EmpolyInfo empolyInfo)
        {
            base.AddObject("EmpolyInfoes", empolyInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemInfoes(ItemInfo itemInfo)
        {
            base.AddObject("ItemInfoes", itemInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the numbers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonumbers(number number)
        {
            base.AddObject("numbers", number);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderInfoes(OrderInfo orderInfo)
        {
            base.AddObject("OrderInfoes", orderInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SaleInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSaleInfoes(SaleInfo saleInfo)
        {
            base.AddObject("SaleInfoes", saleInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SelayInformations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSelayInformations(SelayInformation selayInformation)
        {
            base.AddObject("SelayInformations", selayInformation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="catId">No Metadata Documentation available.</param>
        public ObjectResult<SP_ItemSelection_Result> SP_ItemSelection(Nullable<global::System.Int32> catId)
        {
            ObjectParameter catIdParameter;
            if (catId.HasValue)
            {
                catIdParameter = new ObjectParameter("catId", catId);
            }
            else
            {
                catIdParameter = new ObjectParameter("catId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<SP_ItemSelection_Result>("SP_ItemSelection", catIdParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="CatagoryInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CatagoryInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CatagoryInfo object.
        /// </summary>
        /// <param name="catagoryId">Initial value of the CatagoryId property.</param>
        public static CatagoryInfo CreateCatagoryInfo(global::System.Int32 catagoryId)
        {
            CatagoryInfo catagoryInfo = new CatagoryInfo();
            catagoryInfo.CatagoryId = catagoryId;
            return catagoryInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CatagoryId
        {
            get
            {
                return _CatagoryId;
            }
            set
            {
                if (_CatagoryId != value)
                {
                    OnCatagoryIdChanging(value);
                    ReportPropertyChanging("CatagoryId");
                    _CatagoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CatagoryId");
                    OnCatagoryIdChanged();
                }
            }
        }
        private global::System.Int32 _CatagoryId;
        partial void OnCatagoryIdChanging(global::System.Int32 value);
        partial void OnCatagoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_Name
        {
            get
            {
                return _C_Name;
            }
            set
            {
                OnC_NameChanging(value);
                ReportPropertyChanging("C_Name");
                _C_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_Name");
                OnC_NameChanged();
            }
        }
        private global::System.String _C_Name;
        partial void OnC_NameChanging(global::System.String value);
        partial void OnC_NameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_ItemInfo_CatagoryInfo", "ItemInfo")]
        public EntityCollection<ItemInfo> ItemInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemInfo>("ESTIMATEModel.FK_ItemInfo_CatagoryInfo", "ItemInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemInfo>("ESTIMATEModel.FK_ItemInfo_CatagoryInfo", "ItemInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_SaleInfo_CatagoryInfo", "SaleInfo")]
        public EntityCollection<SaleInfo> SaleInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SaleInfo>("ESTIMATEModel.FK_SaleInfo_CatagoryInfo", "SaleInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SaleInfo>("ESTIMATEModel.FK_SaleInfo_CatagoryInfo", "SaleInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="CustomarInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomarInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomarInfo object.
        /// </summary>
        /// <param name="customarId">Initial value of the CustomarId property.</param>
        public static CustomarInfo CreateCustomarInfo(global::System.Int32 customarId)
        {
            CustomarInfo customarInfo = new CustomarInfo();
            customarInfo.CustomarId = customarId;
            return customarInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomarId
        {
            get
            {
                return _CustomarId;
            }
            set
            {
                if (_CustomarId != value)
                {
                    OnCustomarIdChanging(value);
                    ReportPropertyChanging("CustomarId");
                    _CustomarId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomarId");
                    OnCustomarIdChanged();
                }
            }
        }
        private global::System.Int32 _CustomarId;
        partial void OnCustomarIdChanging(global::System.Int32 value);
        partial void OnCustomarIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_Name
        {
            get
            {
                return _C_Name;
            }
            set
            {
                OnC_NameChanging(value);
                ReportPropertyChanging("C_Name");
                _C_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_Name");
                OnC_NameChanged();
            }
        }
        private global::System.String _C_Name;
        partial void OnC_NameChanging(global::System.String value);
        partial void OnC_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_Address
        {
            get
            {
                return _C_Address;
            }
            set
            {
                OnC_AddressChanging(value);
                ReportPropertyChanging("C_Address");
                _C_Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_Address");
                OnC_AddressChanged();
            }
        }
        private global::System.String _C_Address;
        partial void OnC_AddressChanging(global::System.String value);
        partial void OnC_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C_Phone
        {
            get
            {
                return _C_Phone;
            }
            set
            {
                OnC_PhoneChanging(value);
                ReportPropertyChanging("C_Phone");
                _C_Phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_Phone");
                OnC_PhoneChanged();
            }
        }
        private Nullable<global::System.Int32> _C_Phone;
        partial void OnC_PhoneChanging(Nullable<global::System.Int32> value);
        partial void OnC_PhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String C_Type
        {
            get
            {
                return _C_Type;
            }
            set
            {
                OnC_TypeChanging(value);
                ReportPropertyChanging("C_Type");
                _C_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("C_Type");
                OnC_TypeChanged();
            }
        }
        private global::System.String _C_Type;
        partial void OnC_TypeChanging(global::System.String value);
        partial void OnC_TypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_OrderInfo_CustomarInfo", "OrderInfo")]
        public EntityCollection<OrderInfo> OrderInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderInfo>("ESTIMATEModel.FK_OrderInfo_CustomarInfo", "OrderInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderInfo>("ESTIMATEModel.FK_OrderInfo_CustomarInfo", "OrderInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_SaleInfo_CustomarInfo", "SaleInfo")]
        public EntityCollection<SaleInfo> SaleInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SaleInfo>("ESTIMATEModel.FK_SaleInfo_CustomarInfo", "SaleInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SaleInfo>("ESTIMATEModel.FK_SaleInfo_CustomarInfo", "SaleInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="EmpolyDipartment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmpolyDipartment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmpolyDipartment object.
        /// </summary>
        /// <param name="departmentId">Initial value of the DepartmentId property.</param>
        public static EmpolyDipartment CreateEmpolyDipartment(global::System.Int32 departmentId)
        {
            EmpolyDipartment empolyDipartment = new EmpolyDipartment();
            empolyDipartment.DepartmentId = departmentId;
            return empolyDipartment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentId
        {
            get
            {
                return _DepartmentId;
            }
            set
            {
                if (_DepartmentId != value)
                {
                    OnDepartmentIdChanging(value);
                    ReportPropertyChanging("DepartmentId");
                    _DepartmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DepartmentId");
                    OnDepartmentIdChanged();
                }
            }
        }
        private global::System.Int32 _DepartmentId;
        partial void OnDepartmentIdChanging(global::System.Int32 value);
        partial void OnDepartmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_EmpolyInfo_EmpolyDipartment", "EmpolyInfo")]
        public EntityCollection<EmpolyInfo> EmpolyInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EmpolyInfo>("ESTIMATEModel.FK_EmpolyInfo_EmpolyDipartment", "EmpolyInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EmpolyInfo>("ESTIMATEModel.FK_EmpolyInfo_EmpolyDipartment", "EmpolyInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="EmpolyInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmpolyInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmpolyInfo object.
        /// </summary>
        /// <param name="empolyId">Initial value of the EmpolyId property.</param>
        public static EmpolyInfo CreateEmpolyInfo(global::System.Int32 empolyId)
        {
            EmpolyInfo empolyInfo = new EmpolyInfo();
            empolyInfo.EmpolyId = empolyId;
            return empolyInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmpolyId
        {
            get
            {
                return _EmpolyId;
            }
            set
            {
                if (_EmpolyId != value)
                {
                    OnEmpolyIdChanging(value);
                    ReportPropertyChanging("EmpolyId");
                    _EmpolyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmpolyId");
                    OnEmpolyIdChanged();
                }
            }
        }
        private global::System.Int32 _EmpolyId;
        partial void OnEmpolyIdChanging(global::System.Int32 value);
        partial void OnEmpolyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String E_Name
        {
            get
            {
                return _E_Name;
            }
            set
            {
                OnE_NameChanging(value);
                ReportPropertyChanging("E_Name");
                _E_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("E_Name");
                OnE_NameChanged();
            }
        }
        private global::System.String _E_Name;
        partial void OnE_NameChanging(global::System.String value);
        partial void OnE_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String E_Address
        {
            get
            {
                return _E_Address;
            }
            set
            {
                OnE_AddressChanging(value);
                ReportPropertyChanging("E_Address");
                _E_Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("E_Address");
                OnE_AddressChanged();
            }
        }
        private global::System.String _E_Address;
        partial void OnE_AddressChanging(global::System.String value);
        partial void OnE_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> E_DateOfBirth
        {
            get
            {
                return _E_DateOfBirth;
            }
            set
            {
                OnE_DateOfBirthChanging(value);
                ReportPropertyChanging("E_DateOfBirth");
                _E_DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("E_DateOfBirth");
                OnE_DateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _E_DateOfBirth;
        partial void OnE_DateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnE_DateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> E_JoinDate
        {
            get
            {
                return _E_JoinDate;
            }
            set
            {
                OnE_JoinDateChanging(value);
                ReportPropertyChanging("E_JoinDate");
                _E_JoinDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("E_JoinDate");
                OnE_JoinDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _E_JoinDate;
        partial void OnE_JoinDateChanging(Nullable<global::System.DateTime> value);
        partial void OnE_JoinDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> E_Phone
        {
            get
            {
                return _E_Phone;
            }
            set
            {
                OnE_PhoneChanging(value);
                ReportPropertyChanging("E_Phone");
                _E_Phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("E_Phone");
                OnE_PhoneChanged();
            }
        }
        private Nullable<global::System.Int32> _E_Phone;
        partial void OnE_PhoneChanging(Nullable<global::System.Int32> value);
        partial void OnE_PhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> E_Department
        {
            get
            {
                return _E_Department;
            }
            set
            {
                OnE_DepartmentChanging(value);
                ReportPropertyChanging("E_Department");
                _E_Department = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("E_Department");
                OnE_DepartmentChanged();
            }
        }
        private Nullable<global::System.Int32> _E_Department;
        partial void OnE_DepartmentChanging(Nullable<global::System.Int32> value);
        partial void OnE_DepartmentChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_EmpolyInfo_EmpolyDipartment", "EmpolyDipartment")]
        public EmpolyDipartment EmpolyDipartment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmpolyDipartment>("ESTIMATEModel.FK_EmpolyInfo_EmpolyDipartment", "EmpolyDipartment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmpolyDipartment>("ESTIMATEModel.FK_EmpolyInfo_EmpolyDipartment", "EmpolyDipartment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EmpolyDipartment> EmpolyDipartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmpolyDipartment>("ESTIMATEModel.FK_EmpolyInfo_EmpolyDipartment", "EmpolyDipartment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EmpolyDipartment>("ESTIMATEModel.FK_EmpolyInfo_EmpolyDipartment", "EmpolyDipartment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_SelayInformation_EmpolyInfo", "SelayInformation")]
        public EntityCollection<SelayInformation> SelayInformations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SelayInformation>("ESTIMATEModel.FK_SelayInformation_EmpolyInfo", "SelayInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SelayInformation>("ESTIMATEModel.FK_SelayInformation_EmpolyInfo", "SelayInformation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="ItemInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemInfo object.
        /// </summary>
        /// <param name="itemId">Initial value of the ItemId property.</param>
        public static ItemInfo CreateItemInfo(global::System.Int32 itemId)
        {
            ItemInfo itemInfo = new ItemInfo();
            itemInfo.ItemId = itemId;
            return itemInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemId
        {
            get
            {
                return _ItemId;
            }
            set
            {
                if (_ItemId != value)
                {
                    OnItemIdChanging(value);
                    ReportPropertyChanging("ItemId");
                    _ItemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemId");
                    OnItemIdChanged();
                }
            }
        }
        private global::System.Int32 _ItemId;
        partial void OnItemIdChanging(global::System.Int32 value);
        partial void OnItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String I_Name
        {
            get
            {
                return _I_Name;
            }
            set
            {
                OnI_NameChanging(value);
                ReportPropertyChanging("I_Name");
                _I_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("I_Name");
                OnI_NameChanged();
            }
        }
        private global::System.String _I_Name;
        partial void OnI_NameChanging(global::System.String value);
        partial void OnI_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> I_CatagoryId
        {
            get
            {
                return _I_CatagoryId;
            }
            set
            {
                OnI_CatagoryIdChanging(value);
                ReportPropertyChanging("I_CatagoryId");
                _I_CatagoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_CatagoryId");
                OnI_CatagoryIdChanged();
            }
        }
        private Nullable<global::System.Int32> _I_CatagoryId;
        partial void OnI_CatagoryIdChanging(Nullable<global::System.Int32> value);
        partial void OnI_CatagoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> I_ExoDate
        {
            get
            {
                return _I_ExoDate;
            }
            set
            {
                OnI_ExoDateChanging(value);
                ReportPropertyChanging("I_ExoDate");
                _I_ExoDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_ExoDate");
                OnI_ExoDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _I_ExoDate;
        partial void OnI_ExoDateChanging(Nullable<global::System.DateTime> value);
        partial void OnI_ExoDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> I_MgfDate
        {
            get
            {
                return _I_MgfDate;
            }
            set
            {
                OnI_MgfDateChanging(value);
                ReportPropertyChanging("I_MgfDate");
                _I_MgfDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_MgfDate");
                OnI_MgfDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _I_MgfDate;
        partial void OnI_MgfDateChanging(Nullable<global::System.DateTime> value);
        partial void OnI_MgfDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> I_BuyPrice
        {
            get
            {
                return _I_BuyPrice;
            }
            set
            {
                OnI_BuyPriceChanging(value);
                ReportPropertyChanging("I_BuyPrice");
                _I_BuyPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_BuyPrice");
                OnI_BuyPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _I_BuyPrice;
        partial void OnI_BuyPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnI_BuyPriceChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_ItemInfo_CatagoryInfo", "CatagoryInfo")]
        public CatagoryInfo CatagoryInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CatagoryInfo>("ESTIMATEModel.FK_ItemInfo_CatagoryInfo", "CatagoryInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CatagoryInfo>("ESTIMATEModel.FK_ItemInfo_CatagoryInfo", "CatagoryInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CatagoryInfo> CatagoryInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CatagoryInfo>("ESTIMATEModel.FK_ItemInfo_CatagoryInfo", "CatagoryInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CatagoryInfo>("ESTIMATEModel.FK_ItemInfo_CatagoryInfo", "CatagoryInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_OrderInfo_ItemInfo", "OrderInfo")]
        public EntityCollection<OrderInfo> OrderInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderInfo>("ESTIMATEModel.FK_OrderInfo_ItemInfo", "OrderInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderInfo>("ESTIMATEModel.FK_OrderInfo_ItemInfo", "OrderInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="number")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class number : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new number object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static number Createnumber(global::System.Int32 id)
        {
            number number = new number();
            number.Id = id;
            return number;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="OrderInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderInfo object.
        /// </summary>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        public static OrderInfo CreateOrderInfo(global::System.Int32 orderId)
        {
            OrderInfo orderInfo = new OrderInfo();
            orderInfo.OrderId = orderId;
            return orderInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if (_OrderId != value)
                {
                    OnOrderIdChanging(value);
                    ReportPropertyChanging("OrderId");
                    _OrderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderId");
                    OnOrderIdChanged();
                }
            }
        }
        private global::System.Int32 _OrderId;
        partial void OnOrderIdChanging(global::System.Int32 value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CustomarId
        {
            get
            {
                return _CustomarId;
            }
            set
            {
                OnCustomarIdChanging(value);
                ReportPropertyChanging("CustomarId");
                _CustomarId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomarId");
                OnCustomarIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CustomarId;
        partial void OnCustomarIdChanging(Nullable<global::System.Int32> value);
        partial void OnCustomarIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ItemId
        {
            get
            {
                return _ItemId;
            }
            set
            {
                OnItemIdChanging(value);
                ReportPropertyChanging("ItemId");
                _ItemId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemId");
                OnItemIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ItemId;
        partial void OnItemIdChanging(Nullable<global::System.Int32> value);
        partial void OnItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OrderDate;
        partial void OnOrderDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeliveryDate
        {
            get
            {
                return _DeliveryDate;
            }
            set
            {
                OnDeliveryDateChanging(value);
                ReportPropertyChanging("DeliveryDate");
                _DeliveryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryDate");
                OnDeliveryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeliveryDate;
        partial void OnDeliveryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDeliveryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AdvancePay
        {
            get
            {
                return _AdvancePay;
            }
            set
            {
                OnAdvancePayChanging(value);
                ReportPropertyChanging("AdvancePay");
                _AdvancePay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AdvancePay");
                OnAdvancePayChanged();
            }
        }
        private Nullable<global::System.Decimal> _AdvancePay;
        partial void OnAdvancePayChanging(Nullable<global::System.Decimal> value);
        partial void OnAdvancePayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalMoney
        {
            get
            {
                return _TotalMoney;
            }
            set
            {
                OnTotalMoneyChanging(value);
                ReportPropertyChanging("TotalMoney");
                _TotalMoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalMoney");
                OnTotalMoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalMoney;
        partial void OnTotalMoneyChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalMoneyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_OrderInfo_CustomarInfo", "CustomarInfo")]
        public CustomarInfo CustomarInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomarInfo>("ESTIMATEModel.FK_OrderInfo_CustomarInfo", "CustomarInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomarInfo>("ESTIMATEModel.FK_OrderInfo_CustomarInfo", "CustomarInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CustomarInfo> CustomarInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomarInfo>("ESTIMATEModel.FK_OrderInfo_CustomarInfo", "CustomarInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CustomarInfo>("ESTIMATEModel.FK_OrderInfo_CustomarInfo", "CustomarInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_OrderInfo_ItemInfo", "ItemInfo")]
        public ItemInfo ItemInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemInfo>("ESTIMATEModel.FK_OrderInfo_ItemInfo", "ItemInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemInfo>("ESTIMATEModel.FK_OrderInfo_ItemInfo", "ItemInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ItemInfo> ItemInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemInfo>("ESTIMATEModel.FK_OrderInfo_ItemInfo", "ItemInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ItemInfo>("ESTIMATEModel.FK_OrderInfo_ItemInfo", "ItemInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="SaleInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SaleInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SaleInfo object.
        /// </summary>
        /// <param name="saleId">Initial value of the SaleId property.</param>
        public static SaleInfo CreateSaleInfo(global::System.Int32 saleId)
        {
            SaleInfo saleInfo = new SaleInfo();
            saleInfo.SaleId = saleId;
            return saleInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SaleId
        {
            get
            {
                return _SaleId;
            }
            set
            {
                if (_SaleId != value)
                {
                    OnSaleIdChanging(value);
                    ReportPropertyChanging("SaleId");
                    _SaleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SaleId");
                    OnSaleIdChanged();
                }
            }
        }
        private global::System.Int32 _SaleId;
        partial void OnSaleIdChanging(global::System.Int32 value);
        partial void OnSaleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CustomerId;
        partial void OnCustomerIdChanging(Nullable<global::System.Int32> value);
        partial void OnCustomerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryId;
        partial void OnCategoryIdChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                OnUnitPriceChanging(value);
                ReportPropertyChanging("UnitPrice");
                _UnitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitPrice");
                OnUnitPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _UnitPrice;
        partial void OnUnitPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnUnitPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SaleDate
        {
            get
            {
                return _SaleDate;
            }
            set
            {
                OnSaleDateChanging(value);
                ReportPropertyChanging("SaleDate");
                _SaleDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SaleDate");
                OnSaleDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _SaleDate;
        partial void OnSaleDateChanging(Nullable<global::System.DateTime> value);
        partial void OnSaleDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemName
        {
            get
            {
                return _ItemName;
            }
            set
            {
                OnItemNameChanging(value);
                ReportPropertyChanging("ItemName");
                _ItemName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemName");
                OnItemNameChanged();
            }
        }
        private global::System.String _ItemName;
        partial void OnItemNameChanging(global::System.String value);
        partial void OnItemNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_SaleInfo_CatagoryInfo", "CatagoryInfo")]
        public CatagoryInfo CatagoryInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CatagoryInfo>("ESTIMATEModel.FK_SaleInfo_CatagoryInfo", "CatagoryInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CatagoryInfo>("ESTIMATEModel.FK_SaleInfo_CatagoryInfo", "CatagoryInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CatagoryInfo> CatagoryInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CatagoryInfo>("ESTIMATEModel.FK_SaleInfo_CatagoryInfo", "CatagoryInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CatagoryInfo>("ESTIMATEModel.FK_SaleInfo_CatagoryInfo", "CatagoryInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_SaleInfo_CustomarInfo", "CustomarInfo")]
        public CustomarInfo CustomarInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomarInfo>("ESTIMATEModel.FK_SaleInfo_CustomarInfo", "CustomarInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomarInfo>("ESTIMATEModel.FK_SaleInfo_CustomarInfo", "CustomarInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CustomarInfo> CustomarInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CustomarInfo>("ESTIMATEModel.FK_SaleInfo_CustomarInfo", "CustomarInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CustomarInfo>("ESTIMATEModel.FK_SaleInfo_CustomarInfo", "CustomarInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="SelayInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SelayInformation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SelayInformation object.
        /// </summary>
        /// <param name="selaryId">Initial value of the SelaryId property.</param>
        public static SelayInformation CreateSelayInformation(global::System.Int32 selaryId)
        {
            SelayInformation selayInformation = new SelayInformation();
            selayInformation.SelaryId = selaryId;
            return selayInformation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SelaryId
        {
            get
            {
                return _SelaryId;
            }
            set
            {
                if (_SelaryId != value)
                {
                    OnSelaryIdChanging(value);
                    ReportPropertyChanging("SelaryId");
                    _SelaryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SelaryId");
                    OnSelaryIdChanged();
                }
            }
        }
        private global::System.Int32 _SelaryId;
        partial void OnSelaryIdChanging(global::System.Int32 value);
        partial void OnSelaryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EmployId
        {
            get
            {
                return _EmployId;
            }
            set
            {
                OnEmployIdChanging(value);
                ReportPropertyChanging("EmployId");
                _EmployId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployId");
                OnEmployIdChanged();
            }
        }
        private Nullable<global::System.Int32> _EmployId;
        partial void OnEmployIdChanging(Nullable<global::System.Int32> value);
        partial void OnEmployIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Department
        {
            get
            {
                return _Department;
            }
            set
            {
                OnDepartmentChanging(value);
                ReportPropertyChanging("Department");
                _Department = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Department");
                OnDepartmentChanged();
            }
        }
        private Nullable<global::System.Int32> _Department;
        partial void OnDepartmentChanging(Nullable<global::System.Int32> value);
        partial void OnDepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Ammount
        {
            get
            {
                return _Ammount;
            }
            set
            {
                OnAmmountChanging(value);
                ReportPropertyChanging("Ammount");
                _Ammount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ammount");
                OnAmmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _Ammount;
        partial void OnAmmountChanging(Nullable<global::System.Decimal> value);
        partial void OnAmmountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_SelayInformation_EmpolyInfo", "EmpolyInfo")]
        public EmpolyInfo EmpolyInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmpolyInfo>("ESTIMATEModel.FK_SelayInformation_EmpolyInfo", "EmpolyInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmpolyInfo>("ESTIMATEModel.FK_SelayInformation_EmpolyInfo", "EmpolyInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EmpolyInfo> EmpolyInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EmpolyInfo>("ESTIMATEModel.FK_SelayInformation_EmpolyInfo", "EmpolyInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EmpolyInfo>("ESTIMATEModel.FK_SelayInformation_EmpolyInfo", "EmpolyInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ESTIMATEModel", Name="SP_ItemSelection_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_ItemSelection_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String I_Name
        {
            get
            {
                return _I_Name;
            }
            set
            {
                OnI_NameChanging(value);
                ReportPropertyChanging("I_Name");
                _I_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("I_Name");
                OnI_NameChanged();
            }
        }
        private global::System.String _I_Name;
        partial void OnI_NameChanging(global::System.String value);
        partial void OnI_NameChanged();

        #endregion

    }

    #endregion

    
}
