//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ESTIMATEModel", "FK_StudentInformation_DepartmentInfo", "DepartmentInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BuySallsProject.DepartmentInfo), "StudentInformation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuySallsProject.StudentInformation), true)]
[assembly: EdmRelationshipAttribute("ESTIMATEModel", "FK_StudentInformation_GenderInfo", "GenderInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BuySallsProject.GenderInfo), "StudentInformation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuySallsProject.StudentInformation), true)]
[assembly: EdmRelationshipAttribute("ESTIMATEModel", "FK_StudentInformation_SemisterInfo", "SemisterInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BuySallsProject.SemisterInfo), "StudentInformation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuySallsProject.StudentInformation), true)]
[assembly: EdmRelationshipAttribute("ESTIMATEModel", "FK_StudentInformation_ShiftInfo", "ShiftInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BuySallsProject.ShiftInfo), "StudentInformation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BuySallsProject.StudentInformation), true)]

#endregion

namespace BuySallsProject
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ESTIMATEEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ESTIMATEEntities object using the connection string found in the 'ESTIMATEEntities' section of the application configuration file.
        /// </summary>
        public ESTIMATEEntities() : base("name=ESTIMATEEntities", "ESTIMATEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ESTIMATEEntities object.
        /// </summary>
        public ESTIMATEEntities(string connectionString) : base(connectionString, "ESTIMATEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ESTIMATEEntities object.
        /// </summary>
        public ESTIMATEEntities(EntityConnection connection) : base(connection, "ESTIMATEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DepartmentInfo> DepartmentInfoes
        {
            get
            {
                if ((_DepartmentInfoes == null))
                {
                    _DepartmentInfoes = base.CreateObjectSet<DepartmentInfo>("DepartmentInfoes");
                }
                return _DepartmentInfoes;
            }
        }
        private ObjectSet<DepartmentInfo> _DepartmentInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GenderInfo> GenderInfoes
        {
            get
            {
                if ((_GenderInfoes == null))
                {
                    _GenderInfoes = base.CreateObjectSet<GenderInfo>("GenderInfoes");
                }
                return _GenderInfoes;
            }
        }
        private ObjectSet<GenderInfo> _GenderInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PurposeInfo> PurposeInfoes
        {
            get
            {
                if ((_PurposeInfoes == null))
                {
                    _PurposeInfoes = base.CreateObjectSet<PurposeInfo>("PurposeInfoes");
                }
                return _PurposeInfoes;
            }
        }
        private ObjectSet<PurposeInfo> _PurposeInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SemisterInfo> SemisterInfoes
        {
            get
            {
                if ((_SemisterInfoes == null))
                {
                    _SemisterInfoes = base.CreateObjectSet<SemisterInfo>("SemisterInfoes");
                }
                return _SemisterInfoes;
            }
        }
        private ObjectSet<SemisterInfo> _SemisterInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ShiftInfo> ShiftInfoes
        {
            get
            {
                if ((_ShiftInfoes == null))
                {
                    _ShiftInfoes = base.CreateObjectSet<ShiftInfo>("ShiftInfoes");
                }
                return _ShiftInfoes;
            }
        }
        private ObjectSet<ShiftInfo> _ShiftInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StudentInformation> StudentInformations
        {
            get
            {
                if ((_StudentInformations == null))
                {
                    _StudentInformations = base.CreateObjectSet<StudentInformation>("StudentInformations");
                }
                return _StudentInformations;
            }
        }
        private ObjectSet<StudentInformation> _StudentInformations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DepartmentInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDepartmentInfoes(DepartmentInfo departmentInfo)
        {
            base.AddObject("DepartmentInfoes", departmentInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GenderInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGenderInfoes(GenderInfo genderInfo)
        {
            base.AddObject("GenderInfoes", genderInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PurposeInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPurposeInfoes(PurposeInfo purposeInfo)
        {
            base.AddObject("PurposeInfoes", purposeInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SemisterInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSemisterInfoes(SemisterInfo semisterInfo)
        {
            base.AddObject("SemisterInfoes", semisterInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ShiftInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShiftInfoes(ShiftInfo shiftInfo)
        {
            base.AddObject("ShiftInfoes", shiftInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StudentInformations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudentInformations(StudentInformation studentInformation)
        {
            base.AddObject("StudentInformations", studentInformation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="catId">No Metadata Documentation available.</param>
        public ObjectResult<SP_ItemSelection_Result> SP_ItemSelection(Nullable<global::System.Int32> catId)
        {
            ObjectParameter catIdParameter;
            if (catId.HasValue)
            {
                catIdParameter = new ObjectParameter("catId", catId);
            }
            else
            {
                catIdParameter = new ObjectParameter("catId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<SP_ItemSelection_Result>("SP_ItemSelection", catIdParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="DepartmentInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DepartmentInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DepartmentInfo object.
        /// </summary>
        /// <param name="departmentId">Initial value of the DepartmentId property.</param>
        public static DepartmentInfo CreateDepartmentInfo(global::System.Int32 departmentId)
        {
            DepartmentInfo departmentInfo = new DepartmentInfo();
            departmentInfo.DepartmentId = departmentId;
            return departmentInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentId
        {
            get
            {
                return _DepartmentId;
            }
            set
            {
                if (_DepartmentId != value)
                {
                    OnDepartmentIdChanging(value);
                    ReportPropertyChanging("DepartmentId");
                    _DepartmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DepartmentId");
                    OnDepartmentIdChanged();
                }
            }
        }
        private global::System.Int32 _DepartmentId;
        partial void OnDepartmentIdChanging(global::System.Int32 value);
        partial void OnDepartmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_StudentInformation_DepartmentInfo", "StudentInformation")]
        public EntityCollection<StudentInformation> StudentInformations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentInformation>("ESTIMATEModel.FK_StudentInformation_DepartmentInfo", "StudentInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentInformation>("ESTIMATEModel.FK_StudentInformation_DepartmentInfo", "StudentInformation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="GenderInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GenderInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GenderInfo object.
        /// </summary>
        /// <param name="genderId">Initial value of the GenderId property.</param>
        public static GenderInfo CreateGenderInfo(global::System.Int32 genderId)
        {
            GenderInfo genderInfo = new GenderInfo();
            genderInfo.GenderId = genderId;
            return genderInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenderId
        {
            get
            {
                return _GenderId;
            }
            set
            {
                if (_GenderId != value)
                {
                    OnGenderIdChanging(value);
                    ReportPropertyChanging("GenderId");
                    _GenderId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GenderId");
                    OnGenderIdChanged();
                }
            }
        }
        private global::System.Int32 _GenderId;
        partial void OnGenderIdChanging(global::System.Int32 value);
        partial void OnGenderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GenderName
        {
            get
            {
                return _GenderName;
            }
            set
            {
                OnGenderNameChanging(value);
                ReportPropertyChanging("GenderName");
                _GenderName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GenderName");
                OnGenderNameChanged();
            }
        }
        private global::System.String _GenderName;
        partial void OnGenderNameChanging(global::System.String value);
        partial void OnGenderNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_StudentInformation_GenderInfo", "StudentInformation")]
        public EntityCollection<StudentInformation> StudentInformations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentInformation>("ESTIMATEModel.FK_StudentInformation_GenderInfo", "StudentInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentInformation>("ESTIMATEModel.FK_StudentInformation_GenderInfo", "StudentInformation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="PurposeInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PurposeInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PurposeInfo object.
        /// </summary>
        /// <param name="purposeId">Initial value of the PurposeId property.</param>
        public static PurposeInfo CreatePurposeInfo(global::System.Int32 purposeId)
        {
            PurposeInfo purposeInfo = new PurposeInfo();
            purposeInfo.PurposeId = purposeId;
            return purposeInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PurposeId
        {
            get
            {
                return _PurposeId;
            }
            set
            {
                if (_PurposeId != value)
                {
                    OnPurposeIdChanging(value);
                    ReportPropertyChanging("PurposeId");
                    _PurposeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PurposeId");
                    OnPurposeIdChanged();
                }
            }
        }
        private global::System.Int32 _PurposeId;
        partial void OnPurposeIdChanging(global::System.Int32 value);
        partial void OnPurposeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PurposeName
        {
            get
            {
                return _PurposeName;
            }
            set
            {
                OnPurposeNameChanging(value);
                ReportPropertyChanging("PurposeName");
                _PurposeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PurposeName");
                OnPurposeNameChanged();
            }
        }
        private global::System.String _PurposeName;
        partial void OnPurposeNameChanging(global::System.String value);
        partial void OnPurposeNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="SemisterInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SemisterInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SemisterInfo object.
        /// </summary>
        /// <param name="semisterId">Initial value of the SemisterId property.</param>
        public static SemisterInfo CreateSemisterInfo(global::System.Int32 semisterId)
        {
            SemisterInfo semisterInfo = new SemisterInfo();
            semisterInfo.SemisterId = semisterId;
            return semisterInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SemisterId
        {
            get
            {
                return _SemisterId;
            }
            set
            {
                if (_SemisterId != value)
                {
                    OnSemisterIdChanging(value);
                    ReportPropertyChanging("SemisterId");
                    _SemisterId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SemisterId");
                    OnSemisterIdChanged();
                }
            }
        }
        private global::System.Int32 _SemisterId;
        partial void OnSemisterIdChanging(global::System.Int32 value);
        partial void OnSemisterIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SemisterName
        {
            get
            {
                return _SemisterName;
            }
            set
            {
                OnSemisterNameChanging(value);
                ReportPropertyChanging("SemisterName");
                _SemisterName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SemisterName");
                OnSemisterNameChanged();
            }
        }
        private global::System.String _SemisterName;
        partial void OnSemisterNameChanging(global::System.String value);
        partial void OnSemisterNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_StudentInformation_SemisterInfo", "StudentInformation")]
        public EntityCollection<StudentInformation> StudentInformations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentInformation>("ESTIMATEModel.FK_StudentInformation_SemisterInfo", "StudentInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentInformation>("ESTIMATEModel.FK_StudentInformation_SemisterInfo", "StudentInformation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="ShiftInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ShiftInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShiftInfo object.
        /// </summary>
        /// <param name="shiftId">Initial value of the ShiftId property.</param>
        public static ShiftInfo CreateShiftInfo(global::System.Int32 shiftId)
        {
            ShiftInfo shiftInfo = new ShiftInfo();
            shiftInfo.ShiftId = shiftId;
            return shiftInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShiftId
        {
            get
            {
                return _ShiftId;
            }
            set
            {
                if (_ShiftId != value)
                {
                    OnShiftIdChanging(value);
                    ReportPropertyChanging("ShiftId");
                    _ShiftId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ShiftId");
                    OnShiftIdChanged();
                }
            }
        }
        private global::System.Int32 _ShiftId;
        partial void OnShiftIdChanging(global::System.Int32 value);
        partial void OnShiftIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiftName
        {
            get
            {
                return _ShiftName;
            }
            set
            {
                OnShiftNameChanging(value);
                ReportPropertyChanging("ShiftName");
                _ShiftName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiftName");
                OnShiftNameChanged();
            }
        }
        private global::System.String _ShiftName;
        partial void OnShiftNameChanging(global::System.String value);
        partial void OnShiftNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_StudentInformation_ShiftInfo", "StudentInformation")]
        public EntityCollection<StudentInformation> StudentInformations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentInformation>("ESTIMATEModel.FK_StudentInformation_ShiftInfo", "StudentInformation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentInformation>("ESTIMATEModel.FK_StudentInformation_ShiftInfo", "StudentInformation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="StudentInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StudentInformation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StudentInformation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static StudentInformation CreateStudentInformation(global::System.Int32 id)
        {
            StudentInformation studentInformation = new StudentInformation();
            studentInformation.Id = id;
            return studentInformation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Roll
        {
            get
            {
                return _Roll;
            }
            set
            {
                OnRollChanging(value);
                ReportPropertyChanging("Roll");
                _Roll = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Roll");
                OnRollChanged();
            }
        }
        private Nullable<global::System.Int32> _Roll;
        partial void OnRollChanging(Nullable<global::System.Int32> value);
        partial void OnRollChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Registration
        {
            get
            {
                return _Registration;
            }
            set
            {
                OnRegistrationChanging(value);
                ReportPropertyChanging("Registration");
                _Registration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Registration");
                OnRegistrationChanged();
            }
        }
        private Nullable<global::System.Int32> _Registration;
        partial void OnRegistrationChanging(Nullable<global::System.Int32> value);
        partial void OnRegistrationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SemisterId
        {
            get
            {
                return _SemisterId;
            }
            set
            {
                OnSemisterIdChanging(value);
                ReportPropertyChanging("SemisterId");
                _SemisterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SemisterId");
                OnSemisterIdChanged();
            }
        }
        private Nullable<global::System.Int32> _SemisterId;
        partial void OnSemisterIdChanging(Nullable<global::System.Int32> value);
        partial void OnSemisterIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ShiftId
        {
            get
            {
                return _ShiftId;
            }
            set
            {
                OnShiftIdChanging(value);
                ReportPropertyChanging("ShiftId");
                _ShiftId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShiftId");
                OnShiftIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ShiftId;
        partial void OnShiftIdChanging(Nullable<global::System.Int32> value);
        partial void OnShiftIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DepartmentId
        {
            get
            {
                return _DepartmentId;
            }
            set
            {
                OnDepartmentIdChanging(value);
                ReportPropertyChanging("DepartmentId");
                _DepartmentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartmentId");
                OnDepartmentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DepartmentId;
        partial void OnDepartmentIdChanging(Nullable<global::System.Int32> value);
        partial void OnDepartmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GenderId
        {
            get
            {
                return _GenderId;
            }
            set
            {
                OnGenderIdChanging(value);
                ReportPropertyChanging("GenderId");
                _GenderId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenderId");
                OnGenderIdChanged();
            }
        }
        private Nullable<global::System.Int32> _GenderId;
        partial void OnGenderIdChanging(Nullable<global::System.Int32> value);
        partial void OnGenderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private Nullable<global::System.Int32> _Phone;
        partial void OnPhoneChanging(Nullable<global::System.Int32> value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfBirth;
        partial void OnDateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfBirthChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_StudentInformation_DepartmentInfo", "DepartmentInfo")]
        public DepartmentInfo DepartmentInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DepartmentInfo>("ESTIMATEModel.FK_StudentInformation_DepartmentInfo", "DepartmentInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DepartmentInfo>("ESTIMATEModel.FK_StudentInformation_DepartmentInfo", "DepartmentInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DepartmentInfo> DepartmentInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DepartmentInfo>("ESTIMATEModel.FK_StudentInformation_DepartmentInfo", "DepartmentInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DepartmentInfo>("ESTIMATEModel.FK_StudentInformation_DepartmentInfo", "DepartmentInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_StudentInformation_GenderInfo", "GenderInfo")]
        public GenderInfo GenderInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GenderInfo>("ESTIMATEModel.FK_StudentInformation_GenderInfo", "GenderInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GenderInfo>("ESTIMATEModel.FK_StudentInformation_GenderInfo", "GenderInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GenderInfo> GenderInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GenderInfo>("ESTIMATEModel.FK_StudentInformation_GenderInfo", "GenderInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GenderInfo>("ESTIMATEModel.FK_StudentInformation_GenderInfo", "GenderInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_StudentInformation_SemisterInfo", "SemisterInfo")]
        public SemisterInfo SemisterInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SemisterInfo>("ESTIMATEModel.FK_StudentInformation_SemisterInfo", "SemisterInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SemisterInfo>("ESTIMATEModel.FK_StudentInformation_SemisterInfo", "SemisterInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SemisterInfo> SemisterInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SemisterInfo>("ESTIMATEModel.FK_StudentInformation_SemisterInfo", "SemisterInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SemisterInfo>("ESTIMATEModel.FK_StudentInformation_SemisterInfo", "SemisterInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESTIMATEModel", "FK_StudentInformation_ShiftInfo", "ShiftInfo")]
        public ShiftInfo ShiftInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShiftInfo>("ESTIMATEModel.FK_StudentInformation_ShiftInfo", "ShiftInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShiftInfo>("ESTIMATEModel.FK_StudentInformation_ShiftInfo", "ShiftInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ShiftInfo> ShiftInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShiftInfo>("ESTIMATEModel.FK_StudentInformation_ShiftInfo", "ShiftInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ShiftInfo>("ESTIMATEModel.FK_StudentInformation_ShiftInfo", "ShiftInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESTIMATEModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ESTIMATEModel", Name="SP_ItemSelection_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_ItemSelection_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String I_Name
        {
            get
            {
                return _I_Name;
            }
            set
            {
                OnI_NameChanging(value);
                ReportPropertyChanging("I_Name");
                _I_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("I_Name");
                OnI_NameChanged();
            }
        }
        private global::System.String _I_Name;
        partial void OnI_NameChanging(global::System.String value);
        partial void OnI_NameChanged();

        #endregion

    }

    #endregion

    
}
